server:
  port: 8081

spring:
  application:
    name: tfshz

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL:jdbc:mysql://127.0.0.1:3306/tfshz?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}

  data:
    redis:
      host: ${REDIS_HOST:127.0.0.1}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      lettuce:
        pool:
          enabled: true
          max-active: 10
          max-idle: 10
          min-idle: 1
          time-between-eviction-runs: 10s

  jackson:
    default-property-inclusion: non_null

mybatis-plus:
  type-aliases-package: com.tfsh.entity

logging:
  level:
    com.tfsh: debug
  pattern:
    dateformat: mm:ss.SSS
